apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-nfac
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eozkan-tenant/partner-catalog/partner-catalog-nfac@sha256:6fed0034759094cb0102e83b6b7cd0b40a22472435617e587cf97853f5f3c39f
        name: my-java-springboot
        resources: {}
status: {}
